### ISSUE TITLE
Could not pass event PlayerInteractEvent to Blocks_To_Commands

### ISSUE THREAD

**Issue by 0noca** [ILoveAMac/BlocksToCommands#7]
[20:36:02 ERROR]: Could not pass event PlayerInteractEvent to Blocks_To_Commands vv5.0.0-beta.6
java.lang.NullPointerException: null
        at me.ILoveAMac.BTC.listeners.PlayerInteract.onClick(PlayerInteract.java:37) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor231.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-246]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:470) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.BlockSoil.fallOn(BlockSoil.java:83) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.Entity.a(Entity.java:1046) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.EntityLiving.a(EntityLiving.java:247) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.EntityPlayer.a(EntityPlayer.java:1232) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1200) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by 0noca** [comment]
Using newest paper version, 1.16.3
