### ISSUE TITLE
Could not pass event PlayerInteractEvent to Blocks_To_Commands vv5.0.0-beta.6 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by SpiderAang** [ILoveAMac/BlocksToCommands#8]
```
> [11:55:48] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Blocks_To_Commands vv5.0.0-beta.6
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:483) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:450) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.BlockPressurePlateBinary.b(BlockPressurePlateBinary.java:78) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:66) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:59) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:547) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.Entity.checkBlockCollisions(Entity.java:912) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.Entity.move(Entity.java:646) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1024) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NullPointerException
```

**Comment by daronhudson** [comment]
This is still an ongoing issue. I don't believe it causes any real problems, but it absolutely fills your console with that null event exception spam. An update for this would be fantastic.

**Comment by Fyrlex** [comment]
I am also having this problem, can it be fixed soon?
